import {LAB_SETS,SPELLS} from './content.js';
import {MagicStage} from './stage.js';
import {KEEPSAKE_LIMIT,normalizeKeptScene,keptSceneObjects,keepsakeSaveState,sceneName} from './keepsakes.js';

const node=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
const identity=status=>`${status.mode}:${status.accountId||''}`;
export class KeepsakeView{
 constructor({dialog,store,say,account,assets,images,look,onSaved,onPlay,onCreate}){
  Object.assign(this,{dialog,store,say,account,assets,images,look,onSaved,onPlay,onCreate});this.rows=[];this.available=true;this.epoch=0;this.busy=false;this.draft=null;this.editId=null;this.removeId=null;this.name='';this.replaceId='';this.message='';this.interaction=0;this.opener=null;this.owner=identity(account.status());this.revoked=false;
  dialog.addEventListener('pointerdown',()=>this.interaction++);dialog.addEventListener('keydown',()=>this.interaction++);
  dialog.addEventListener('cancel',e=>{e.preventDefault();this.close();});dialog.addEventListener('close',()=>{if(!dialog.open){this.epoch++;this.draft=null;this.editId=null;this.removeId=null;this.restoreFocus();}});
  this.unsubscribe=account.subscribe?.(status=>{if(status.phase==='stopped'||identity(status)!==this.owner){this.revoked=true;this.epoch++;this.rows=[];this.available=false;this.draft=null;this.editId=null;this.removeId=null;this.name='';this.replaceId='';this.message='';if(dialog.open)dialog.close();dialog.replaceChildren();}else if(dialog.open)this.status();});
 }
 button(text,fn,cls='small-button',disabled=this.busy,key=''){const b=node('button',cls,text);b.type='button';b.disabled=disabled;if(key)b.dataset.keepsakeFocus=key;b.onclick=fn;return b;}
 restoreFocus(){if(this.opener?.isConnected&&!this.opener.disabled&&this.opener.getClientRects().length&&!document.querySelector('dialog[open]'))this.opener.focus({preventScroll:true});}
 close(){this.epoch++;if(this.dialog.open)this.dialog.close();this.restoreFocus();}
 open(opener,{capture=null}={}){
  if(this.revoked)capture=null;
  this.epoch++;this.opener=opener||document.activeElement;this.message='';this.lastFailure=false;this.editId=null;this.removeId=null;this.replaceId='';this.draft=capture?normalizeKeptScene({...capture,id:crypto.randomUUID(),name:this.say('My little magic','나의 작은 마법'),createdAt:new Date().toISOString()}):null;this.name=this.draft?.name||'';this.read();this.paint();if(!this.dialog.open)this.dialog.showModal();this.dialog.querySelector(this.draft?'#keepsake-name':'#keepsake-title')?.focus({preventScroll:true});
 }
 read(){const result=this.store.read();this.available=result.available;this.rows=result.scenes;return result;}
 status(){
  const target=this.dialog.querySelector('#keepsake-sync');if(!target)return;const state=this.revoked?'stopped':!this.available?'unavailable':this.lastFailure?'failed':keepsakeSaveState(this.account.status());const text={unavailable:this.say('Your collection could not be read, so its save state cannot be confirmed.','보관함을 읽지 못해 저장 상태를 확인할 수 없어요.'),failed:this.say('This change could not be saved. Your existing scenes stay.','이번 변경을 저장하지 못했어요. 기존 보관 장면은 유지해요.'),guest:this.say('Guest scenes stay on this browser. Sign in with SYNK ID to keep them across devices.','로그인 전 체험 장면은 이 브라우저에 보관해요. SYNK ID로 연결하면 다른 기기에서도 이어갈 수 있어요.'),synced:this.say('Your scenes are saved to your SYNK account.','장면 보관함이 SYNK 계정에 저장됐어요.'),pending:this.say('Account saving is still in progress. Check the save status above.','아직 계정에 저장 중이에요. 화면 위의 저장 상태를 확인해 주세요.'),offline:this.say('Not saved to your account yet. Your pending change stays on this device.','아직 계정에 저장하지 못했어요. 이 기기에 보관한 변경은 연결 후 다시 전송해요.'),conflict:this.say('Another device changed your progress. Choose which progress to keep on your account page.','다른 기기의 진행도 바뀌었어요. 계정 화면에서 사용할 기록을 골라 주세요.'),stopped:this.say('The account connection ended. Reconnect with SYNK ID before changing this collection.','계정 연결이 끝났어요. SYNK ID로 다시 연결한 뒤 보관함을 바꿔 주세요.')}[state];target.dataset.state=state;target.textContent=text;
 }
 thumbnail(scene,canvas){const epoch=this.epoch,raw=normalizeKeptScene(scene);if(!raw)return;Promise.resolve(this.assets()).then(()=>{if(epoch!==this.epoch||!this.dialog.open||!canvas.isConnected)return;const picture=new MagicStage(canvas,document.createElement('div'),()=>{});canvas.width=480;canvas.height=270;picture.pixelRatio=.5;picture.ctx=canvas.getContext('2d');picture.ctx.setTransform(.5,0,0,.5,0,0);picture.images=this.images();picture.appearance(this.look());picture.set(keptSceneObjects(raw),{chapter:0,animate:false,labels:{}});}).catch(()=>{if(epoch===this.epoch&&canvas.isConnected){canvas.setAttribute('aria-label',this.say('Scene preview unavailable','장면 미리보기를 준비하지 못했어요'));}});}
 picture(scene){const figure=node('figure','keepsake-picture'),canvas=node('canvas');canvas.width=480;canvas.height=270;canvas.setAttribute('role','img');canvas.setAttribute('aria-label',scene.name);figure.append(canvas);this.thumbnail(scene,canvas);return figure;}
 async run(action,{success='',focus='',onSuccess=null,saveChange=true}={}){
  if(this.busy)return;const epoch=this.epoch,moved=this.interaction,owner=identity(this.account.status());this.busy=true;this.message='';this.paint();let result;
  try{result=await action();}catch{result={ok:false,reason:'storage'};}this.busy=false;
  if(identity(this.account.status())!==owner)return;
  if(result?.ok&&result.scenes)this.onSaved(result.scenes);
  if(epoch!==this.epoch||!this.dialog.open){if(this.dialog.open){this.read();this.paint();}return;}
  if(saveChange)this.lastFailure=!result?.ok;if(result?.ok){onSuccess?.();result.afterClose?.();this.message=success;}else this.message=this.error(result?.reason);if(epoch!==this.epoch||!this.dialog.open)return;this.read();this.paint();if(focus&&moved===this.interaction)this.dialog.querySelector(`[data-keepsake-focus="${focus}"]`)?.focus({preventScroll:true});
 }
 error(reason){return reason==='full'?this.say('Six scenes are kept. Choose a scene to replace, or remove one first.','6개를 보관 중이에요. 교체할 장면을 직접 고르거나 먼저 하나를 지워 주세요.'):reason==='missing-scene'?this.say('This scene changed in another tab. Read your collection again.','다른 탭에서 이 장면이 바뀌었어요. 보관함을 다시 읽어 주세요.'):reason==='conflict'?this.say('Choose which account progress to keep before saving this scene. Your new name is still here.','계정에서 사용할 기록을 먼저 골라 주세요. 입력한 이름은 그대로예요.'):reason==='not-owned'?this.say('This picnic set is not in your wallet. The saved scene stays here; the free workshop is always available.','지금 보유하지 않은 소풍 세트예요. 보관 장면은 그대로 두고 무료 기본 실험실에서 놀 수 있어요.'):reason==='not-introduced'?this.say('First meet two words in the free adventure, then return to this scene.','무료 모험에서 두 표현을 먼저 익힌 뒤 이 장면으로 돌아와 주세요.'):reason==='audio'?this.say('Could not prepare the sounds. Your scene is safe. Tap to try again.','소리를 준비하지 못했어요. 장면은 그대로예요. 다시 눌러 주세요.'):reason==='stopped'?this.say('The account connection ended. Reconnect before changing saved scenes.','계정 연결이 끝났어요. 다시 연결한 뒤 보관함을 바꿔 주세요.'):this.say('Could not save the change. Your scene and typed name are still here. Try again.','변경을 저장하지 못했어요. 장면과 입력한 이름은 그대로예요. 다시 시도해 주세요.');}
 paint(){
  const active=this.dialog.contains(document.activeElement)?document.activeElement:null,focus=active?.dataset.keepsakeFocus,position=active?.selectionStart;const body=node('div','keepsake-body'),heading=node('div','keepsake-heading'),title=node('h2','','');title.id='keepsake-title';title.tabIndex=-1;title.textContent=this.say('My magic scenes','내가 만든 마법 장면');heading.append(title,this.button(this.say('Close','닫기'),()=>this.close(),'small-button',false,'close'));body.append(heading,node('p','keepsake-intro',this.say('Keep up to six scenes for free. Open one and change it again with your Korean words. Your current backdrop and frame stay on.','내가 만든 장면 6개를 무료로 간직해요. 다시 꺼내 배운 말로 바꿔 보세요. 지금 장착한 배경과 사진틀은 그대로 사용해요.')));
  const status=node('p','keepsake-sync');status.id='keepsake-sync';status.setAttribute('role','status');body.append(status);
  const account=this.account.status(),blocked=this.revoked||identity(account)!==this.owner||account.mode==='account'&&['conflict','stopped','loading'].includes(account.phase);const disabled=this.busy||!this.available||blocked;
  if(!this.available)body.append(node('p','keepsake-error',this.say('Your collection could not be read. No saved scene has been removed.','보관함을 읽지 못했어요. 저장된 장면을 지우지는 않았어요.')));
  body.append(this.button(this.say('Read saved scenes again','보관함 다시 읽기'),()=>{this.message='';this.read();this.paint();},'text-button',this.busy,'read'));
  if(this.draft||this.editId){
   const form=node('form','keepsake-form'),edited=this.rows.find(row=>row.id===this.editId),label=node('label','',this.say('Scene name','장면 이름')),input=node('input');input.id='keepsake-name';input.type='text';input.maxLength=30;input.disabled=this.busy||blocked;input.value=this.name;input.dataset.keepsakeFocus='name';input.oninput=()=>{this.name=input.value;};label.append(input);form.append(node('h3','',this.editId?this.say('Rename this scene','이 장면 이름 바꾸기'):this.say('Keep this moment','이 장면 간직하기')),label);
   if(this.draft)form.append(this.picture(this.draft));else if(edited)form.append(this.picture(edited));
   const replacing=this.draft&&this.rows.length>=KEEPSAKE_LIMIT;if(replacing){const replaceLabel=node('label','',this.say('Choose one scene to replace','교체할 장면을 직접 골라 주세요')),select=node('select');select.id='keepsake-replace';select.dataset.keepsakeFocus='replace';const placeholder=node('option','',this.say('Choose a saved scene…','보관한 장면 고르기…'));placeholder.value='';select.append(placeholder,...this.rows.map(row=>{const o=node('option','',row.name);o.value=row.id;return o;}));select.value=this.replaceId;select.onchange=()=>{this.replaceId=select.value;this.paint();};replaceLabel.append(select);form.append(replaceLabel,node('p','keepsake-small',this.say('Only the scene you choose will be replaced. The other five stay.','직접 고른 장면만 새 장면으로 바꿔요. 나머지 다섯 장면은 유지해요.')));}
   const save=this.button(this.editId?this.say('Save the new name','새 이름 저장'):replacing?this.say('Replace the selected scene','고른 장면 교체하기'):this.say('Keep this scene','이 장면 보관하기'),null,'main-button',disabled||replacing&&!this.replaceId,'save');save.type='submit';form.onsubmit=e=>{e.preventDefault();if(save.disabled)return;const name=sceneName(this.name);if(!name){this.message=this.say('Give this scene a short name.','이 장면에 짧은 이름을 붙여 주세요.');this.paint();this.dialog.querySelector('#keepsake-name')?.focus();return;}const editedId=this.editId,scene=this.draft?{...this.draft,name}:null;void this.run(()=>editedId?this.store.rename(editedId,name):this.store.save(scene,this.replaceId||null),{success:this.say('Your scene is in the collection. Check the account save status above.','보관함에 장면을 남겼어요. 위의 계정 저장 상태를 확인해 주세요.'),focus:editedId?`play:${editedId}`:`play:${scene.id}`,onSuccess:()=>{this.draft=null;this.editId=null;this.name='';this.replaceId='';}});};form.append(save,this.button(this.say('Cancel','취소'),()=>{this.draft=null;this.editId=null;this.name='';this.replaceId='';this.paint();},'text-button',this.busy,'cancel-edit'));body.append(form);
  }
  if(this.removeId){const item=this.rows.find(row=>row.id===this.removeId);if(item){const confirm=node('section','keepsake-confirm');confirm.append(node('h3','',this.say(`Remove “${item.name}”?`,`‘${item.name}’ 장면을 지울까요?`)),node('p','',this.say('This removes this kept scene. Your current workshop and adventure stay.','이 보관 장면만 지워요. 지금 실험실과 하던 모험은 유지해요.')),this.button(this.say('Keep this scene','장면 유지'),()=>{this.removeId=null;this.paint();},'secondary-button',this.busy,'cancel-remove'),this.button(this.say('Remove this scene','이 장면 삭제'),()=>{const id=this.removeId;void this.run(()=>this.store.remove(id),{success:this.say('Removed the selected scene.','고른 보관 장면을 지웠어요.'),focus:'read',onSuccess:()=>{this.removeId=null;}});},'small-button',disabled,'confirm-remove'));body.append(confirm);}}
  const message=node('p','keepsake-message',this.message);message.id='keepsake-message';message.setAttribute('role','status');body.append(message);
  const grid=node('div','keepsake-grid');for(const scene of this.rows){const card=node('article','keepsake-card');card.dataset.keepsakeId=scene.id;card.append(this.picture(scene),node('h3','',scene.name),node('p','keepsake-small',this.say(LAB_SETS[scene.set].en,LAB_SETS[scene.set].ko)),node('p','keepsake-words',scene.words.map(word=>SPELLS[word].ko).join(' · ')));const actions=node('div','keepsake-actions');actions.append(this.button(this.say('Play with this scene','이 장면으로 놀기'),()=>{const epoch=this.epoch,owner=identity(this.account.status());void this.run(()=>this.onPlay(scene,()=>epoch===this.epoch&&this.dialog.open&&owner===identity(this.account.status())),{onSuccess:()=>this.close(),saveChange:false});},'secondary-button',disabled,`play:${scene.id}`),this.button(this.say('Rename','이름 바꾸기'),()=>{this.draft=null;this.removeId=null;this.editId=scene.id;this.name=scene.name;this.paint();this.dialog.querySelector('#keepsake-name')?.focus();},'small-button',disabled,`rename:${scene.id}`),this.button(this.say('Remove','삭제'),()=>{this.removeId=scene.id;this.paint();this.dialog.querySelector('[data-keepsake-focus="cancel-remove"]')?.focus();},'text-button',disabled,`remove:${scene.id}`));card.append(actions);grid.append(card);}body.append(grid);
  if(!this.rows.length&&!this.draft)body.append(node('p','keepsake-empty',this.say('Your first kept scene starts in the playground. Make a giant book or lift a little umbrella.','실험실에서 첫 장면을 만들어 보세요. 커다란 책이나 위로 올라간 작은 우산을 간직할 수 있어요.')),this.button(this.say('Make a scene in the free workshop','무료 실험실에서 장면 만들기'),()=>{this.close();this.onCreate();},'secondary-button',this.busy||blocked,'create'));
  this.dialog.replaceChildren(body);this.status();if(focus){const replacement=this.dialog.querySelector(`[data-keepsake-focus="${focus}"]`);if(replacement&&!replacement.disabled){replacement.focus({preventScroll:true});if(typeof position==='number'&&replacement.setSelectionRange)replacement.setSelectionRange(position,position);}}
 }
}
