// 입장 검사 — 근무지·안내문·손님 원고. 자체 창작한 초급 읽기 연습이며 공식 기출이나 검수된 급수별 문항이 아니다.
// TOPIK I 읽기 40~45번(안내문을 읽고 맞지 않는 것·같은 것 고르기)의 능력을 '규칙을 손님에게 적용하기'로 연습한다.
// 정답(answer)은 'pass' 또는 위반한 규칙 id 하나다. 한 손님은 규칙을 많아야 하나 어긴다.

export const CAST = {
  bear: { name: '김보리', label: '곰', age: 21, scale: 1, img: 'assets/cast/bear.webp' },
  raccoon: { name: '나구리', label: '너구리', age: 45, scale: .98, img: 'assets/cast/raccoon.webp' },
  rabbit: { name: '박토순', label: '토끼', age: 72, scale: .9, img: 'assets/cast/rabbit.webp' },
  fox: { name: '여우진', label: '여우', age: 31, scale: 1, img: 'assets/cast/fox.webp' },
  squirrel: { name: '도다미', label: '다람쥐', age: 6, scale: .64, img: 'assets/cast/squirrel.webp' },
  hedgehog: { name: '고도치', label: '고슴도치', age: 9, scale: .72, img: 'assets/cast/hedgehog.webp' },
  penguin: { name: '남콩이', label: '펭귄', age: 24, scale: .9, img: 'assets/cast/penguin.webp' },
  ducks: { name: '오순', label: '오리', age: 34, scale: .94, img: 'assets/cast/ducks.webp', wide: true },
  otter: { name: '수달수', label: '수달', age: 62, scale: .92, img: 'assets/cast/otter.webp' },
  deer: { name: '노나래', label: '사슴', age: 26, scale: 1.04, img: 'assets/cast/deer.webp' },
  panda: { name: '이단비', label: '판다', age: 15, scale: .9, img: 'assets/cast/panda.webp' },
  sheep: { name: '양솜이', label: '양', age: 22, scale: .94, img: 'assets/cast/sheep.webp' },
};

export const ITEMS = {
  'swim-cap': '수영 모자', 'water-bottle': '물병', gimbap: '김밥', snack: '과자', towel: '수건', 'swim-ring': '튜브',
  'library-card': '도서관 카드', 'pool-card': '수영장 카드', book: '책', 'coffee-lid': '커피(뚜껑 있음)',
  'coffee-open': '커피(뚜껑 없음)', camera: '카메라', phone: '휴대폰', purse: '작은 가방', 'picnic-mat': '돗자리',
  chair: '접이식 의자', umbrella: '우산',
};

// 이름은 공통 지도(strata/topik-i.skills.json)와 같게 쓴다. 다른 게임·허브의 추천 이유와 같은 말로 보인다.
export const SKILL_LABEL = {
  'ko.reading.detail': '읽고 세부 정보 찾기',
  'ko.reading.negation': '읽고 부정·변경 이해하기',
  'ko.reading.condition': '읽고 조건 이해하기',
};

const R = (id, text, skill, short) => ({ id, text, skill, short });
const doc = (title, rows, kind = 'ticket') => ({ title, rows, kind });

export const VENUES = [
  {
    id: 'pool', day: 1, name: '하늘 수영장', scene: 'pool', band: 'lapis', date: '8월 6일 수요일',
    briefing: '오늘이 첫 근무예요. 안내문은 세 줄뿐이니까 걱정하지 마세요. 손님의 표와 짐을 안내문과 하나씩 맞춰 봐요.',
    notice: {
      kind: '이용 안내', title: '하늘 수영장 이용 안내',
      rules: [
        R('cap', '수영 모자를 꼭 써야 합니다.', 'ko.reading.detail', '수영 모자'),
        R('food', '음식은 가지고 들어갈 수 없습니다. 물은 괜찮습니다.', 'ko.reading.negation', '음식'),
        R('kid', '7살 이하 어린이는 어른과 함께 들어와야 합니다.', 'ko.reading.condition', '7살 이하 어린이'),
      ],
    },
    cases: [
      { id: 'pool-01', at: '14:02', who: 'bear', doc: doc('하늘 수영장 입장권', [['이름', '김보리'], ['구분', '어른 · 21살'], ['날짜', '8월 6일']]),
        items: ['swim-cap', 'towel'], line: '안녕하세요! 수영하러 왔어요.', answer: 'pass', skill: 'ko.reading.detail', difficulty: 1,
        look: 'items', evidence: ['cap'], why: '수영 모자가 있어요. 음식도 없어요. 그래서 통과예요.',
        reply: '고마워요! 그럼 시원하게 한번 수영해 볼게요!', oops: '보리 씨가 고개를 갸웃했어요. “모자도 있고 음식도 없는데… 왜 안 돼요?”' },
      { id: 'pool-02', at: '14:06', who: 'raccoon', doc: doc('하늘 수영장 입장권', [['이름', '나구리'], ['구분', '어른 · 45살'], ['날짜', '8월 6일']]),
        items: ['swim-cap', 'gimbap'], line: '점심은 수영장 안에서 먹을 거예요.', answer: 'food', skill: 'ko.reading.negation', difficulty: 1,
        look: 'items', evidence: ['food'], why: '김밥은 음식이에요. 음식은 가지고 들어갈 수 없어요.',
        reply: '아이고, 깜빡했네. 김밥은 밖에서 먹고 올게요.', oops: '잠시 뒤, 구리 씨가 물가에서 몰래 김밥을 먹다가 안전 요원에게 딱 걸렸어요!' },
      { id: 'pool-03', at: '14:11', who: 'rabbit', doc: doc('하늘 수영장 입장권', [['이름', '박토순'], ['구분', '어른 · 72살'], ['날짜', '8월 6일']]),
        items: ['swim-cap', 'water-bottle'], line: '물은 가지고 가도 되지요?', answer: 'pass', skill: 'ko.reading.condition', difficulty: 1,
        look: 'items', evidence: ['food'], why: '안내문에 “물은 괜찮습니다”라고 쓰여 있어요.',
        reply: '고마워요. 미끄러우니까 천천히 걸어갈게요.', oops: '토순 할머니가 안내문을 손가락으로 짚었어요. “여기, 물은 괜찮다고 쓰여 있잖아요.”' },
      { id: 'pool-04', at: '14:15', who: 'fox', doc: doc('하늘 수영장 입장권', [['이름', '여우진'], ['구분', '어른 · 31살'], ['날짜', '8월 6일']]),
        items: ['towel', 'water-bottle'], line: '모자는 집에 두고 왔어요. 그냥 들어가도 되지요?', answer: 'cap', skill: 'ko.reading.detail', difficulty: 1,
        look: 'line', evidence: ['cap'], why: '수영 모자를 꼭 써야 해요. 우진 씨는 모자가 없어요.',
        reply: '아, 그렇군요. 매점에서 모자를 하나 살게요.', oops: '잠시 뒤, 모자 없이 들어간 우진 씨가 안전 요원의 호루라기 소리에 다시 나왔어요.' },
      { id: 'pool-05', at: '14:20', who: 'squirrel', doc: doc('하늘 수영장 입장권', [['이름', '도다미'], ['구분', '어린이 · 6살'], ['날짜', '8월 6일']]),
        items: ['swim-cap', 'swim-ring'], line: '아빠는 주차장에 있어요. 저 먼저 들어갈게요!', answer: 'kid', skill: 'ko.reading.condition', difficulty: 2,
        look: 'doc', evidence: ['kid'], why: '다미는 6살이에요. 7살 이하 어린이는 어른과 함께 들어와야 해요.',
        reply: '네! 아빠 데리고 올게요!', oops: '다미가 혼자 물가로 달려가서, 안전 요원이 깜짝 놀라 뛰어왔어요.' },
      { id: 'pool-06', at: '14:24', who: 'hedgehog', doc: doc('하늘 수영장 입장권', [['이름', '고도치'], ['구분', '어린이 · 9살'], ['날짜', '8월 6일']]),
        items: ['swim-cap', 'towel'], line: '저 혼자 왔어요. 아홉 살이에요!', answer: 'pass', skill: 'ko.reading.condition', difficulty: 2,
        look: 'doc', evidence: ['kid'], why: '어른과 함께 와야 하는 건 7살 이하예요. 도치는 9살이라 혼자 들어갈 수 있어요.',
        reply: '야호! 고마워요!', oops: '도치가 표를 번쩍 들어 보였어요. “저는 아홉 살인데요?”' },
      { id: 'pool-07', at: '14:29', who: 'penguin', doc: doc('하늘 수영장 입장권', [['이름', '남콩이'], ['구분', '어른 · 24살'], ['날짜', '8월 6일']]),
        items: ['swim-cap', 'water-bottle', 'snack'], line: '물만 가지고 왔어요.', answer: 'food', skill: 'ko.reading.negation', difficulty: 2,
        look: 'items', evidence: ['food'], why: '물은 괜찮지만 과자는 음식이에요. 짐에 과자가 있어요.',
        reply: '앗, 과자가 들어 있었네요. 맡겨 둘게요.', oops: '잠시 뒤, 콩이 씨가 물가에서 과자 봉지를 뜯다가 안전 요원과 눈이 딱 마주쳤어요.' },
      { id: 'pool-08', at: '14:33', who: 'ducks', doc: doc('하늘 수영장 입장권', [['이름', '오순 외 1명'], ['구분', '어른 1명 · 어린이 1명(5살)'], ['날짜', '8월 6일']]),
        items: [['swim-cap', 2], 'swim-ring'], line: '아이와 같이 왔어요.', answer: 'pass', skill: 'ko.reading.condition', difficulty: 1,
        look: 'doc', evidence: ['kid'], why: '5살 아이가 어른과 함께 왔어요. 모자도 두 개 있어요.',
        reply: '고마워요. 아이 손을 꼭 잡을게요.', oops: '아기 오리가 울먹였어요. “엄마랑 같이 왔는데요!”' },
    ],
  },
  {
    id: 'library', day: 2, name: '별빛 도서관', scene: 'library', band: 'coral', date: '8월 7일 목요일',
    briefing: '오늘은 도서관이 일찍 문을 닫는 날이에요. 시계를 자주 보고, 카드에 적힌 이름도 꼭 확인해요.',
    notice: {
      kind: '이용 안내', title: '별빛 도서관 이용 안내',
      rules: [
        R('card', '도서관 카드가 있어야 들어갈 수 있습니다. 다른 사람의 카드는 쓸 수 없습니다.', 'ko.reading.detail', '도서관 카드'),
        R('food', '음식은 가지고 들어갈 수 없습니다. 음료는 뚜껑이 있으면 괜찮습니다.', 'ko.reading.condition', '음식·뚜껑 없는 음료'),
        R('time', '오늘은 오후 6시에 문을 닫습니다. 오후 5시 30분부터는 들어올 수 없습니다.', 'ko.reading.detail', '5시 30분부터 입장 안 됨'),
      ],
    },
    cases: [
      { id: 'library-01', at: '16:52', who: 'bear', doc: doc('별빛 도서관 카드', [['이름', '김보리'], ['카드 번호', '2041-0715']], 'card'),
        items: ['book'], line: '책을 돌려주러 왔어요.', answer: 'pass', skill: 'ko.reading.detail', difficulty: 1,
        look: 'doc', evidence: ['card'], why: '보리 씨의 도서관 카드가 있어요. 시간도 괜찮아요.',
        reply: '고마워요. 다음 책도 빌려 갈게요.', oops: '보리 씨가 카드를 다시 내밀었어요. “이거 제 카드 맞는데요?”' },
      { id: 'library-02', at: '16:57', who: 'raccoon', doc: null,
        items: ['book'], line: '카드는 집에 있어요. 오늘만 그냥 들어가면 안 돼요?', answer: 'card', skill: 'ko.reading.detail', difficulty: 1,
        look: 'line', evidence: ['card'], why: '도서관 카드가 있어야 들어갈 수 있어요. 구리 씨는 카드가 없어요.',
        reply: '그럼 1층에서 카드를 새로 만들게요.', oops: '잠시 뒤, 관장님이 “카드 없이 들어온 분 계세요?” 하고 찾으러 나왔어요.' },
      { id: 'library-03', at: '17:01', who: 'rabbit', doc: doc('별빛 도서관 카드', [['이름', '박토순'], ['카드 번호', '1953-0402']], 'card'),
        items: ['coffee-lid'], line: '커피는 뚜껑을 꼭 닫았어요.', answer: 'pass', skill: 'ko.reading.condition', difficulty: 2,
        look: 'items', evidence: ['food'], why: '음료는 뚜껑이 있으면 괜찮아요. 할머니 커피에는 뚜껑이 있어요.',
        reply: '고마워요. 조용히 읽다 갈게요.', oops: '토순 할머니가 컵 뚜껑을 톡톡 두드렸어요. “뚜껑이 있으면 괜찮다고 쓰여 있잖아요.”' },
      { id: 'library-04', at: '17:06', who: 'fox', doc: doc('별빛 도서관 카드', [['이름', '여우진'], ['카드 번호', '1994-1120']], 'card'),
        items: ['coffee-open', 'book'], line: '커피 한 잔만 들고 갈게요.', answer: 'food', skill: 'ko.reading.condition', difficulty: 2,
        look: 'items', evidence: ['food'], why: '음료는 뚜껑이 있어야 해요. 우진 씨 커피에는 뚜껑이 없어요.',
        reply: '아, 뚜껑을 받아 올게요.', oops: '잠시 뒤, 우진 씨가 책 위에 커피를 쏟았어요!' },
      { id: 'library-05', at: '17:10', who: 'squirrel', doc: doc('하늘 수영장 회원 카드', [['이름', '도다미'], ['카드 번호', 'S-0612']], 'pool-card'),
        items: [], line: '이 카드도 되지요? 제 카드예요!', answer: 'card', skill: 'ko.reading.detail', difficulty: 2,
        look: 'doc', evidence: ['card'], why: '이건 수영장 카드예요. 도서관에는 도서관 카드가 있어야 해요.',
        reply: '아, 수영장 카드였네요. 엄마랑 도서관 카드를 만들게요.', oops: '다미가 수영장 카드를 내밀자, 사서 선생님이 웃음을 꾹 참았어요.' },
      { id: 'library-06', at: '17:14', who: 'penguin', doc: doc('별빛 도서관 카드', [['이름', '남콩이'], ['카드 번호', '2002-0311']], 'card'),
        items: ['gimbap'], line: '배가 고파서 김밥을 샀어요.', answer: 'food', skill: 'ko.reading.negation', difficulty: 1,
        look: 'items', evidence: ['food'], why: '김밥은 음식이에요. 음식은 가지고 들어갈 수 없어요.',
        reply: '아, 배고픈데… 밖에서 먹고 올게요.', oops: '잠시 뒤, 조용한 도서관에 고소한 김밥 냄새가 퍼졌어요.' },
      { id: 'library-07', at: '17:19', who: 'panda', doc: doc('별빛 도서관 카드', [['이름', '이단아'], ['카드 번호', '2008-0923']], 'card'),
        items: ['book'], line: '이 카드는 언니 거예요. 괜찮지요?', answer: 'card', skill: 'ko.reading.detail', difficulty: 2,
        look: 'doc', evidence: ['card'], why: '카드의 이름은 이단아예요. 다른 사람의 카드는 쓸 수 없어요.',
        reply: '죄송해요… 제 카드를 만들어 올게요.', oops: '잠시 뒤, 단비의 언니가 “내 카드 어디 갔지?” 하며 도서관에 왔어요.' },
      { id: 'library-08', at: '17:26', who: 'hedgehog', doc: doc('별빛 도서관 카드', [['이름', '고도치'], ['카드 번호', '2017-0505']], 'card'),
        items: ['book'], line: '숙제할 책을 빌리고 싶어요.', answer: 'pass', skill: 'ko.reading.detail', difficulty: 2,
        look: 'clock', evidence: ['time'], why: '지금은 5시 26분이에요. 5시 30분 전이라 들어갈 수 있어요.',
        reply: '고마워요! 빨리 고를게요.', oops: '도치가 시계를 가리켰어요. “아직 5시 30분 전인데요?”' },
      { id: 'library-09', at: '17:34', who: 'otter', doc: doc('별빛 도서관 카드', [['이름', '수달수'], ['카드 번호', '1964-0101']], 'card'),
        items: ['book'], line: '잠깐이면 돼요. 책만 빌릴게요.', answer: 'time', skill: 'ko.reading.detail', difficulty: 2,
        look: 'clock', evidence: ['time'], why: '지금은 5시 34분이에요. 5시 30분부터는 들어올 수 없어요.',
        reply: '허허, 그럼 내일 일찍 올게요.', oops: '직원이 문을 닫으려다, 책장 사이의 할아버지를 찾느라 늦게 퇴근했어요.' },
    ],
  },
  {
    id: 'museum', day: 3, name: '바람 미술관', scene: 'museum', band: 'lapis', date: '8월 8일 금요일',
    briefing: '오늘은 특별 전시가 열려서 손님이 많아요. 표의 종류와 나이, 그리고 입장 시간을 잘 봐요.',
    notice: {
      kind: '특별 전시', title: '바람 미술관 「바다의 색」 안내',
      rules: [
        R('time', '관람은 오후 6시까지입니다. 입장은 오후 5시까지만 할 수 있습니다.', 'ko.reading.detail', '입장은 5시까지'),
        R('camera', '카메라는 가지고 들어갈 수 없습니다. 휴대폰은 괜찮습니다.', 'ko.reading.negation', '카메라'),
        R('fee', '어린이 표는 13살 이하만 쓸 수 있습니다. 65살 이상은 무료입니다.', 'ko.reading.condition', '표와 나이'),
      ],
    },
    cases: [
      { id: 'museum-01', at: '16:22', who: 'deer', doc: doc('바람 미술관 관람권', [['이름', '노나래'], ['표', '어른'], ['나이', '26살']]),
        items: ['phone', 'purse'], line: '사진은 안 찍을게요. 휴대폰만 있어요.', answer: 'pass', skill: 'ko.reading.condition', difficulty: 1,
        look: 'items', evidence: ['camera'], why: '휴대폰은 괜찮아요. 카메라는 없어요.',
        reply: '고마워요. 바다 그림을 천천히 볼게요.', oops: '나래 씨가 휴대폰을 들어 보였어요. “휴대폰은 괜찮다고 쓰여 있는데요?”' },
      { id: 'museum-02', at: '16:27', who: 'sheep', doc: doc('바람 미술관 관람권', [['이름', '양솜이'], ['표', '어른'], ['나이', '22살']]),
        items: ['camera', 'purse'], line: '바다 그림을 꼭 찍고 싶어요!', answer: 'camera', skill: 'ko.reading.negation', difficulty: 1,
        look: 'items', evidence: ['camera'], why: '카메라는 가지고 들어갈 수 없어요.',
        reply: '아쉽지만 카메라는 보관함에 맡길게요.', oops: '잠시 뒤, 전시실에서 찰칵! 소리가 나서 모두 돌아봤어요.' },
      { id: 'museum-03', at: '16:32', who: 'panda', doc: doc('바람 미술관 관람권', [['이름', '이단비'], ['표', '어린이'], ['나이', '15살']]),
        items: [], line: '저는 중학생이에요. 어린이 표로 샀어요.', answer: 'fee', skill: 'ko.reading.condition', difficulty: 2,
        look: 'doc', evidence: ['fee'], why: '어린이 표는 13살 이하만 쓸 수 있어요. 단비는 15살이에요.',
        reply: '아, 어른 표로 바꿔 올게요.', oops: '매표소 직원이 달려와서 단비의 표를 바꿔 줬어요.' },
      { id: 'museum-04', at: '16:37', who: 'rabbit', doc: doc('바람 미술관 관람권', [['이름', '박토순'], ['표', '무료'], ['나이', '72살']]),
        items: [], line: '할머니는 무료지요?', answer: 'pass', skill: 'ko.reading.condition', difficulty: 1,
        look: 'doc', evidence: ['fee'], why: '65살 이상은 무료예요. 할머니는 72살이에요.',
        reply: '고마워요. 젊을 때 바다를 많이 봤어요.', oops: '토순 할머니가 안내문을 가리켰어요. “65살 이상은 무료라고 쓰여 있어요.”' },
      { id: 'museum-05', at: '16:43', who: 'otter', doc: doc('바람 미술관 관람권', [['이름', '수달수'], ['표', '무료'], ['나이', '62살']]),
        items: [], line: '저도 할아버지인데, 무료지요?', answer: 'fee', skill: 'ko.reading.condition', difficulty: 2,
        look: 'doc', evidence: ['fee'], why: '무료는 65살 이상이에요. 달수 할아버지는 62살이에요.',
        reply: '허허, 3년만 더 기다릴게요.', oops: '잠시 뒤, 매표소 직원이 “할아버지, 표를 사셔야 해요!” 하고 따라왔어요.' },
      { id: 'museum-06', at: '16:48', who: 'hedgehog', doc: doc('바람 미술관 관람권', [['이름', '고도치'], ['표', '어린이'], ['나이', '9살']]),
        items: [], line: '엄마가 표를 사 줬어요!', answer: 'pass', skill: 'ko.reading.condition', difficulty: 1,
        look: 'doc', evidence: ['fee'], why: '도치는 9살이라 어린이 표를 쓸 수 있어요.',
        reply: '고마워요! 큰 고래 그림부터 볼래요.', oops: '도치가 표를 꼭 쥐었어요. “저는 아홉 살인데요?”' },
      { id: 'museum-07', at: '16:55', who: 'raccoon', doc: doc('바람 미술관 관람권', [['이름', '나구리'], ['표', '어른'], ['나이', '45살']]),
        items: ['camera', 'phone'], line: '카메라는 가방에 넣을게요. 안 찍으면 되지요?', answer: 'camera', skill: 'ko.reading.negation', difficulty: 2,
        look: 'items', evidence: ['camera'], why: '찍지 않아도 카메라는 가지고 들어갈 수 없어요.',
        reply: '알겠어요. 보관함에 넣고 올게요.', oops: '잠시 뒤, 구리 씨가 그림 앞에서 가방 속 카메라를 슬쩍 꺼냈어요.' },
      { id: 'museum-08', at: '17:04', who: 'bear', doc: doc('바람 미술관 관람권', [['이름', '김보리'], ['표', '어른'], ['나이', '21살']]),
        items: ['phone'], line: '전시를 보러 왔어요. 아직 괜찮지요?', answer: 'time', skill: 'ko.reading.detail', difficulty: 2,
        look: 'clock', evidence: ['time'], why: '지금은 5시 4분이에요. 입장은 5시까지만 할 수 있어요.',
        reply: '아쉬워요. 내일은 일찍 올게요.', oops: '보리 씨가 들어가자마자 직원이 불러 세웠어요. “입장 시간이 지났어요!”' },
    ],
  },
  {
    id: 'concert', day: 4, name: '노을 공원 음악회', scene: 'concert', band: 'butter', date: '8월 10일 일요일',
    briefing: '어제 비가 와서 음악회가 하루 미뤄졌어요. 근무 중에 새 알림이 올 수도 있으니 꼭 읽어요.',
    notice: {
      kind: '공연 안내', title: '노을 공원 여름 음악회',
      rules: [
        R('date', '비 때문에 음악회가 8월 10일(일)로 바뀌었습니다. 8월 9일 표로 들어올 수 있습니다.', 'ko.reading.negation', '날짜'),
        R('chair', '돗자리는 가지고 와도 됩니다. 의자는 가지고 올 수 없습니다.', 'ko.reading.negation', '의자'),
        R('kid', '7살 이하 어린이는 보호자와 함께 와야 합니다.', 'ko.reading.condition', '7살 이하 어린이'),
      ],
    },
    memo: { at: '18:25', rule: R('food', '지금부터 음식은 가지고 들어갈 수 없습니다. 물은 괜찮습니다.', 'ko.reading.negation', '음식(알림)'),
      title: '6시 25분 알림', from: '공원 관리실' },
    cases: [
      { id: 'concert-01', at: '18:03', who: 'sheep', doc: doc('여름 음악회 입장권', [['이름', '양솜이'], ['날짜', '8월 9일 토요일'], ['구분', '어른']]),
        items: ['picnic-mat'], line: '어제 비가 와서 오늘 왔어요.', answer: 'pass', skill: 'ko.reading.negation', difficulty: 2,
        look: 'doc', evidence: ['date'], why: '음악회가 10일로 바뀌었고, 9일 표로 들어올 수 있어요.',
        reply: '고마워요! 앞자리에 돗자리를 펼게요.', oops: '솜이 씨가 안내문을 가리켰어요. “9일 표로 들어올 수 있다고 쓰여 있어요.”' },
      { id: 'concert-02', at: '18:08', who: 'fox', doc: doc('여름 음악회 입장권', [['이름', '여우진'], ['날짜', '8월 9일 토요일'], ['구분', '어른']]),
        items: ['chair'], line: '의자에 앉아서 보고 싶어요.', answer: 'chair', skill: 'ko.reading.negation', difficulty: 1,
        look: 'items', evidence: ['chair'], why: '의자는 가지고 올 수 없어요. 돗자리는 괜찮아요.',
        reply: '그럼 의자는 차에 두고 올게요.', oops: '잠시 뒤, 우진 씨 의자 때문에 뒷사람이 무대를 못 봤어요.' },
      { id: 'concert-03', at: '18:13', who: 'penguin', doc: doc('여름 음악회 입장권', [['이름', '남콩이'], ['날짜', '8월 16일 토요일'], ['구분', '어른']]),
        items: [], line: '오늘 음악회 맞지요?', answer: 'date', skill: 'ko.reading.detail', difficulty: 2,
        look: 'doc', evidence: ['date'], why: '콩이 씨 표는 8월 16일 표예요. 오늘 음악회는 8월 9일 표로 들어와요.',
        reply: '앗, 다음 주 표였네요! 다음 주에 올게요.', oops: '잠시 뒤, 콩이 씨가 앉은 자리에 진짜 주인이 나타났어요.' },
      { id: 'concert-04', at: '18:19', who: 'bear', doc: doc('여름 음악회 입장권', [['이름', '김보리'], ['날짜', '8월 9일 토요일'], ['구분', '어른']]),
        items: ['snack', 'picnic-mat'], line: '과자 먹으면서 들을 거예요.', answer: 'pass', skill: 'ko.reading.detail', difficulty: 2,
        look: 'items', evidence: ['chair'], why: '돗자리는 가지고 와도 돼요. 이때는 아직 음식 알림이 오기 전이에요.',
        reply: '고마워요! 친구랑 나눠 먹을게요.', oops: '보리 씨가 안내문을 다시 읽었어요. “과자 이야기는 없는데요?”' },
      { id: 'concert-05', at: '18:28', who: 'raccoon', doc: doc('여름 음악회 입장권', [['이름', '나구리'], ['날짜', '8월 9일 토요일'], ['구분', '어른']]),
        items: ['gimbap', 'picnic-mat'], line: '김밥 도시락을 싸 왔어요.', answer: 'food', skill: 'ko.reading.negation', difficulty: 2,
        look: 'items', evidence: ['food'], why: '6시 25분에 온 알림부터는 음식을 가지고 들어갈 수 없어요.',
        reply: '아이고, 그럼 여기서 다 먹고 들어갈게요.', oops: '잠시 뒤, 방송이 나왔어요. “김밥을 드시는 손님, 관리실로 와 주세요.”' },
      { id: 'concert-06', at: '18:33', who: 'rabbit', doc: doc('여름 음악회 입장권', [['이름', '박토순'], ['날짜', '8월 9일 토요일'], ['구분', '어른']]),
        items: ['water-bottle', 'picnic-mat'], line: '물 한 병만 가지고 왔어요.', answer: 'pass', skill: 'ko.reading.condition', difficulty: 2,
        look: 'items', evidence: ['food'], why: '음식은 안 되지만 물은 괜찮아요.',
        reply: '고마워요. 노래를 들으면 젊어지는 것 같아요.', oops: '토순 할머니가 알림을 가리켰어요. “물은 괜찮다고 쓰여 있어요.”' },
      { id: 'concert-07', at: '18:38', who: 'squirrel', doc: doc('여름 음악회 입장권', [['이름', '도다미'], ['날짜', '8월 9일 토요일'], ['구분', '어린이 · 6살']]),
        items: [], line: '언니는 다음 버스로 와요. 먼저 들어갈게요!', answer: 'kid', skill: 'ko.reading.condition', difficulty: 2,
        look: 'doc', evidence: ['kid'], why: '다미는 6살이에요. 7살 이하 어린이는 보호자와 함께 와야 해요.',
        reply: '네, 언니 오면 같이 들어갈게요!', oops: '다미가 혼자 사람들 사이로 들어가서 언니가 한참 찾았어요.' },
      { id: 'concert-08', at: '18:44', who: 'ducks', doc: doc('여름 음악회 입장권', [['이름', '오순 외 1명'], ['날짜', '8월 9일 토요일'], ['구분', '어른 1명 · 어린이 1명(5살)']]),
        items: ['picnic-mat'], line: '아이랑 돗자리에 앉아서 볼게요.', answer: 'pass', skill: 'ko.reading.condition', difficulty: 1,
        look: 'doc', evidence: ['kid'], why: '5살 아이가 보호자와 함께 왔어요. 돗자리도 괜찮아요.',
        reply: '고마워요. 아이가 노래를 좋아해요.', oops: '아기 오리가 엄마 날개를 꼭 잡았어요. “엄마랑 같이 왔어요!”' },
      { id: 'concert-09', at: '18:50', who: 'otter', doc: doc('여름 음악회 입장권', [['이름', '수달수'], ['날짜', '8월 9일 토요일'], ['구분', '어른']]),
        items: ['chair'], line: '아주 작은 의자예요. 괜찮지요?', answer: 'chair', skill: 'ko.reading.negation', difficulty: 2,
        look: 'items', evidence: ['chair'], why: '작아도 의자는 가지고 올 수 없어요.',
        reply: '허허, 그럼 돗자리를 빌려 올게요.', oops: '잠시 뒤, 할아버지 의자가 다른 손님들의 길을 막았어요.' },
    ],
  },
];

export const SHIFT_SIZE = 6;
