// Existing seven-game catalogue recovered verbatim from learning-hub/collection.js on 2026-10-08.
export const PLAY_GAMES = Object.freeze([
  {
    "id": "racing",
    "name": "한국어 레이싱",
    "combo": 3,
    "comboLabel": "한 레이스에서 정답 게이트 3개 연속 통과",
    "titles": [
      "첫 출발",
      "길을 읽는 드라이버",
      "정답 질주",
      "코스트 마스터"
    ]
  },
  {
    "id": "rhythm",
    "name": "말의 리듬",
    "combo": 30,
    "comboLabel": "한 곡에서 리듬 노트 30콤보",
    "titles": [
      "첫 박자",
      "소리를 모으는 사람",
      "리듬을 타는 귀",
      "완벽한 앙코르"
    ]
  },
  {
    "id": "runner",
    "name": "바람길",
    "combo": 3,
    "comboLabel": "한 판에서 부탁 3개 연속 성공",
    "titles": [
      "첫 바람",
      "부탁을 모으는 여행자",
      "바람을 잇는 발걸음",
      "등불의 길잡이"
    ]
  },
  {
    "id": "order-rush",
    "name": "주문 폭주",
    "combo": 5,
    "comboLabel": "한 영업에서 주문 5개 연속 성공",
    "titles": [
      "첫 영업",
      "주문을 기억하는 손",
      "빈틈없는 바리스타",
      "완벽한 마감"
    ]
  },
  {
    "id": "entry-check",
    "name": "입장 검사",
    "combo": 5,
    "comboLabel": "한 근무에서 첫 도장 5개 연속 정답",
    "titles": [
      "첫 근무",
      "초대장을 읽는 눈",
      "정확한 도장",
      "믿음직한 문지기"
    ]
  },
  {
    "id": "story-classroom",
    "name": "선생님이 돌아왔다",
    "combo": 3,
    "comboLabel": "한 이야기에서 도움 없이 부탁 3개 연속 첫 시도 성공",
    "titles": [
      "첫 이야기",
      "교실의 해결사",
      "척척 이야기꾼",
      "완벽한 마지막 장"
    ]
  },
  {
    "id": "blank-slice",
    "name": "빈칸 베기",
    "combo": 5,
    "comboLabel": "한 판에서 정답 5개 연속 베기",
    "titles": [
      "첫 베기",
      "표현을 모으는 검객",
      "끊김 없는 검무",
      "빈칸의 달인"
    ]
  }
]);
export const PLAY_ACHIEVEMENTS = Object.freeze([
  {
    "key": "first",
    "name": "첫 완주",
    "description": "한국어 레이싱 한 판 끝까지 마치기",
    "metric": "rounds",
    "target": 1,
    "id": "racing-first",
    "game": "racing",
    "rewardId": "racing-title-first",
    "title": "첫 출발"
  },
  {
    "key": "steady",
    "name": "차곡차곡 20",
    "description": "누적 정답 20개",
    "metric": "correct",
    "target": 20,
    "id": "racing-steady",
    "game": "racing",
    "rewardId": "racing-title-steady",
    "title": "길을 읽는 드라이버"
  },
  {
    "key": "combo",
    "name": "흐름을 잇다",
    "description": "한 레이스에서 정답 게이트 3개 연속 통과",
    "metric": "bestCombo",
    "target": 3,
    "id": "racing-combo",
    "game": "racing",
    "rewardId": "racing-title-combo",
    "title": "정답 질주"
  },
  {
    "key": "perfect",
    "name": "세 번의 완벽한 판",
    "description": "한 판의 문제를 모두 맞힌 판 3회",
    "metric": "perfectRounds",
    "target": 3,
    "id": "racing-perfect",
    "game": "racing",
    "rewardId": "racing-title-perfect",
    "title": "코스트 마스터"
  },
  {
    "key": "first",
    "name": "첫 완주",
    "description": "말의 리듬 한 판 끝까지 마치기",
    "metric": "rounds",
    "target": 1,
    "id": "rhythm-first",
    "game": "rhythm",
    "rewardId": "rhythm-title-first",
    "title": "첫 박자"
  },
  {
    "key": "steady",
    "name": "차곡차곡 20",
    "description": "듣기 문제 누적 정답 20개",
    "metric": "correct",
    "target": 20,
    "id": "rhythm-steady",
    "game": "rhythm",
    "rewardId": "rhythm-title-steady",
    "title": "소리를 모으는 사람"
  },
  {
    "key": "combo",
    "name": "흐름을 잇다",
    "description": "한 곡에서 리듬 노트 30콤보",
    "metric": "bestCombo",
    "target": 30,
    "id": "rhythm-combo",
    "game": "rhythm",
    "rewardId": "rhythm-title-combo",
    "title": "리듬을 타는 귀"
  },
  {
    "key": "perfect",
    "name": "세 번의 완벽한 판",
    "description": "한 곡의 듣기 문제를 모두 맞힌 판 3회",
    "metric": "perfectRounds",
    "target": 3,
    "id": "rhythm-perfect",
    "game": "rhythm",
    "rewardId": "rhythm-title-perfect",
    "title": "완벽한 앙코르"
  },
  {
    "key": "first",
    "name": "첫 완주",
    "description": "바람길 한 판 끝까지 마치기",
    "metric": "rounds",
    "target": 1,
    "id": "runner-first",
    "game": "runner",
    "rewardId": "runner-title-first",
    "title": "첫 바람"
  },
  {
    "key": "steady",
    "name": "차곡차곡 20",
    "description": "누적 정답 20개",
    "metric": "correct",
    "target": 20,
    "id": "runner-steady",
    "game": "runner",
    "rewardId": "runner-title-steady",
    "title": "부탁을 모으는 여행자"
  },
  {
    "key": "combo",
    "name": "흐름을 잇다",
    "description": "한 판에서 부탁 3개 연속 성공",
    "metric": "bestCombo",
    "target": 3,
    "id": "runner-combo",
    "game": "runner",
    "rewardId": "runner-title-combo",
    "title": "바람을 잇는 발걸음"
  },
  {
    "key": "perfect",
    "name": "세 번의 완벽한 판",
    "description": "한 판의 문제를 모두 맞힌 판 3회",
    "metric": "perfectRounds",
    "target": 3,
    "id": "runner-perfect",
    "game": "runner",
    "rewardId": "runner-title-perfect",
    "title": "등불의 길잡이"
  },
  {
    "key": "first",
    "name": "첫 완주",
    "description": "주문 폭주 한 판 끝까지 마치기",
    "metric": "rounds",
    "target": 1,
    "id": "order-rush-first",
    "game": "order-rush",
    "rewardId": "order-rush-title-first",
    "title": "첫 영업"
  },
  {
    "key": "steady",
    "name": "차곡차곡 20",
    "description": "누적 정답 20개",
    "metric": "correct",
    "target": 20,
    "id": "order-rush-steady",
    "game": "order-rush",
    "rewardId": "order-rush-title-steady",
    "title": "주문을 기억하는 손"
  },
  {
    "key": "combo",
    "name": "흐름을 잇다",
    "description": "한 영업에서 주문 5개 연속 성공",
    "metric": "bestCombo",
    "target": 5,
    "id": "order-rush-combo",
    "game": "order-rush",
    "rewardId": "order-rush-title-combo",
    "title": "빈틈없는 바리스타"
  },
  {
    "key": "perfect",
    "name": "세 번의 완벽한 판",
    "description": "한 판의 문제를 모두 맞힌 판 3회",
    "metric": "perfectRounds",
    "target": 3,
    "id": "order-rush-perfect",
    "game": "order-rush",
    "rewardId": "order-rush-title-perfect",
    "title": "완벽한 마감"
  },
  {
    "key": "first",
    "name": "첫 완주",
    "description": "입장 검사 한 판 끝까지 마치기",
    "metric": "rounds",
    "target": 1,
    "id": "entry-check-first",
    "game": "entry-check",
    "rewardId": "entry-check-title-first",
    "title": "첫 근무"
  },
  {
    "key": "steady",
    "name": "차곡차곡 20",
    "description": "누적 정답 20개",
    "metric": "correct",
    "target": 20,
    "id": "entry-check-steady",
    "game": "entry-check",
    "rewardId": "entry-check-title-steady",
    "title": "초대장을 읽는 눈"
  },
  {
    "key": "combo",
    "name": "흐름을 잇다",
    "description": "한 근무에서 첫 도장 5개 연속 정답",
    "metric": "bestCombo",
    "target": 5,
    "id": "entry-check-combo",
    "game": "entry-check",
    "rewardId": "entry-check-title-combo",
    "title": "정확한 도장"
  },
  {
    "key": "perfect",
    "name": "세 번의 완벽한 판",
    "description": "한 판의 문제를 모두 맞힌 판 3회",
    "metric": "perfectRounds",
    "target": 3,
    "id": "entry-check-perfect",
    "game": "entry-check",
    "rewardId": "entry-check-title-perfect",
    "title": "믿음직한 문지기"
  },
  {
    "key": "first",
    "name": "첫 완주",
    "description": "선생님이 돌아왔다 한 판 끝까지 마치기",
    "metric": "rounds",
    "target": 1,
    "id": "story-classroom-first",
    "game": "story-classroom",
    "rewardId": "story-classroom-title-first",
    "title": "첫 이야기"
  },
  {
    "key": "steady",
    "name": "차곡차곡 20",
    "description": "도움 없이 첫 시도에 옮긴 부탁 누적 20개",
    "metric": "correct",
    "target": 20,
    "id": "story-classroom-steady",
    "game": "story-classroom",
    "rewardId": "story-classroom-title-steady",
    "title": "교실의 해결사"
  },
  {
    "key": "combo",
    "name": "흐름을 잇다",
    "description": "한 이야기에서 도움 없이 부탁 3개 연속 첫 시도 성공",
    "metric": "bestCombo",
    "target": 3,
    "id": "story-classroom-combo",
    "game": "story-classroom",
    "rewardId": "story-classroom-title-combo",
    "title": "척척 이야기꾼"
  },
  {
    "key": "perfect",
    "name": "세 번의 완벽한 판",
    "description": "모든 부탁을 도움 없이 첫 시도에 옮긴 이야기 3회",
    "metric": "perfectRounds",
    "target": 3,
    "id": "story-classroom-perfect",
    "game": "story-classroom",
    "rewardId": "story-classroom-title-perfect",
    "title": "완벽한 마지막 장"
  },
  {
    "key": "first",
    "name": "첫 완주",
    "description": "빈칸 베기 한 판 끝까지 마치기",
    "metric": "rounds",
    "target": 1,
    "id": "blank-slice-first",
    "game": "blank-slice",
    "rewardId": "blank-slice-title-first",
    "title": "첫 베기"
  },
  {
    "key": "steady",
    "name": "차곡차곡 20",
    "description": "누적 정답 베기 20개",
    "metric": "correct",
    "target": 20,
    "id": "blank-slice-steady",
    "game": "blank-slice",
    "rewardId": "blank-slice-title-steady",
    "title": "표현을 모으는 검객"
  },
  {
    "key": "combo",
    "name": "흐름을 잇다",
    "description": "한 판에서 정답 5개 연속 베기",
    "metric": "bestCombo",
    "target": 5,
    "id": "blank-slice-combo",
    "game": "blank-slice",
    "rewardId": "blank-slice-title-combo",
    "title": "끊김 없는 검무"
  },
  {
    "key": "perfect",
    "name": "세 번의 완벽한 판",
    "description": "한 판의 문제를 모두 맞힌 판 3회",
    "metric": "perfectRounds",
    "target": 3,
    "id": "blank-slice-perfect",
    "game": "blank-slice",
    "rewardId": "blank-slice-title-perfect",
    "title": "빈칸의 달인"
  }
]);
export const GAME_SHOP_ITEMS = Object.freeze([
  {
    "id": "racing-style-default",
    "kind": "game-style",
    "game": "racing",
    "slot": "style",
    "value": "default",
    "name": "기본 꾸미기",
    "price": 0,
    "description": "처음 함께한 기본 모습이에요.",
    "color": "#b7cdbb"
  },
  {
    "id": "racing-title-first",
    "kind": "game-title",
    "game": "racing",
    "slot": "title",
    "value": "first",
    "name": "첫 출발",
    "price": null,
    "unlockOnly": true,
    "description": "한국어 레이싱 한 판 끝까지 마치기",
    "color": "#d4b786",
    "achievementId": "racing-first"
  },
  {
    "id": "racing-title-steady",
    "kind": "game-title",
    "game": "racing",
    "slot": "title",
    "value": "steady",
    "name": "길을 읽는 드라이버",
    "price": null,
    "unlockOnly": true,
    "description": "누적 정답 20개",
    "color": "#d4b786",
    "achievementId": "racing-steady"
  },
  {
    "id": "racing-title-combo",
    "kind": "game-title",
    "game": "racing",
    "slot": "title",
    "value": "combo",
    "name": "정답 질주",
    "price": null,
    "unlockOnly": true,
    "description": "한 레이스에서 정답 게이트 3개 연속 통과",
    "color": "#d4b786",
    "achievementId": "racing-combo"
  },
  {
    "id": "racing-title-perfect",
    "kind": "game-title",
    "game": "racing",
    "slot": "title",
    "value": "perfect",
    "name": "코스트 마스터",
    "price": null,
    "unlockOnly": true,
    "description": "한 판의 문제를 모두 맞힌 판 3회",
    "color": "#d4b786",
    "achievementId": "racing-perfect"
  },
  {
    "id": "rhythm-style-default",
    "kind": "game-style",
    "game": "rhythm",
    "slot": "style",
    "value": "default",
    "name": "기본 꾸미기",
    "price": 0,
    "description": "처음 함께한 기본 모습이에요.",
    "color": "#b7cdbb"
  },
  {
    "id": "rhythm-style-aurora",
    "kind": "game-style",
    "game": "rhythm",
    "slot": "style",
    "value": "aurora",
    "name": "오로라 비트",
    "price": 25,
    "description": "노트와 타격 빛을 청록빛 오로라로 바꿔요.",
    "color": "#78d7c1"
  },
  {
    "id": "rhythm-style-sunset",
    "kind": "game-style",
    "game": "rhythm",
    "slot": "style",
    "value": "sunset",
    "name": "노을 스테이지",
    "price": 60,
    "description": "노트와 타격 빛을 따뜻한 노을빛으로 바꿔요.",
    "color": "#efa177"
  },
  {
    "id": "rhythm-style-starlight",
    "kind": "game-style",
    "game": "rhythm",
    "slot": "style",
    "value": "starlight",
    "name": "별빛 앙코르",
    "price": 100,
    "description": "노트와 타격 빛을 보랏빛 별무리로 바꿔요.",
    "color": "#c2b7ef"
  },
  {
    "id": "rhythm-title-first",
    "kind": "game-title",
    "game": "rhythm",
    "slot": "title",
    "value": "first",
    "name": "첫 박자",
    "price": null,
    "unlockOnly": true,
    "description": "말의 리듬 한 판 끝까지 마치기",
    "color": "#d4b786",
    "achievementId": "rhythm-first"
  },
  {
    "id": "rhythm-title-steady",
    "kind": "game-title",
    "game": "rhythm",
    "slot": "title",
    "value": "steady",
    "name": "소리를 모으는 사람",
    "price": null,
    "unlockOnly": true,
    "description": "듣기 문제 누적 정답 20개",
    "color": "#d4b786",
    "achievementId": "rhythm-steady"
  },
  {
    "id": "rhythm-title-combo",
    "kind": "game-title",
    "game": "rhythm",
    "slot": "title",
    "value": "combo",
    "name": "리듬을 타는 귀",
    "price": null,
    "unlockOnly": true,
    "description": "한 곡에서 리듬 노트 30콤보",
    "color": "#d4b786",
    "achievementId": "rhythm-combo"
  },
  {
    "id": "rhythm-title-perfect",
    "kind": "game-title",
    "game": "rhythm",
    "slot": "title",
    "value": "perfect",
    "name": "완벽한 앙코르",
    "price": null,
    "unlockOnly": true,
    "description": "한 곡의 듣기 문제를 모두 맞힌 판 3회",
    "color": "#d4b786",
    "achievementId": "rhythm-perfect"
  },
  {
    "id": "runner-style-default",
    "kind": "game-style",
    "game": "runner",
    "slot": "style",
    "value": "default",
    "name": "기본 꾸미기",
    "price": 0,
    "description": "처음 함께한 기본 모습이에요.",
    "color": "#b7cdbb"
  },
  {
    "id": "runner-title-first",
    "kind": "game-title",
    "game": "runner",
    "slot": "title",
    "value": "first",
    "name": "첫 바람",
    "price": null,
    "unlockOnly": true,
    "description": "바람길 한 판 끝까지 마치기",
    "color": "#d4b786",
    "achievementId": "runner-first"
  },
  {
    "id": "runner-title-steady",
    "kind": "game-title",
    "game": "runner",
    "slot": "title",
    "value": "steady",
    "name": "부탁을 모으는 여행자",
    "price": null,
    "unlockOnly": true,
    "description": "누적 정답 20개",
    "color": "#d4b786",
    "achievementId": "runner-steady"
  },
  {
    "id": "runner-title-combo",
    "kind": "game-title",
    "game": "runner",
    "slot": "title",
    "value": "combo",
    "name": "바람을 잇는 발걸음",
    "price": null,
    "unlockOnly": true,
    "description": "한 판에서 부탁 3개 연속 성공",
    "color": "#d4b786",
    "achievementId": "runner-combo"
  },
  {
    "id": "runner-title-perfect",
    "kind": "game-title",
    "game": "runner",
    "slot": "title",
    "value": "perfect",
    "name": "등불의 길잡이",
    "price": null,
    "unlockOnly": true,
    "description": "한 판의 문제를 모두 맞힌 판 3회",
    "color": "#d4b786",
    "achievementId": "runner-perfect"
  },
  {
    "id": "order-rush-style-default",
    "kind": "game-style",
    "game": "order-rush",
    "slot": "style",
    "value": "default",
    "name": "기본 꾸미기",
    "price": 0,
    "description": "처음 함께한 기본 모습이에요.",
    "color": "#b7cdbb"
  },
  {
    "id": "order-rush-style-mint",
    "kind": "game-style",
    "game": "order-rush",
    "slot": "style",
    "value": "mint",
    "name": "민트 카페",
    "price": 25,
    "description": "작업대 앞 펠트 판·매트·컵 받침을 민트빛으로 꾸며요.",
    "color": "#90cbbb"
  },
  {
    "id": "order-rush-style-coral",
    "kind": "game-style",
    "game": "order-rush",
    "slot": "style",
    "value": "coral",
    "name": "코랄 카페",
    "price": 60,
    "description": "작업대 앞 펠트 판·매트·컵 받침을 산호빛으로 꾸며요.",
    "color": "#e3a498"
  },
  {
    "id": "order-rush-style-night",
    "kind": "game-style",
    "game": "order-rush",
    "slot": "style",
    "value": "night",
    "name": "밤하늘 카페",
    "price": 100,
    "description": "작업대 앞 펠트 판·매트·컵 받침을 밤하늘빛으로 꾸며요.",
    "color": "#929bc5"
  },
  {
    "id": "order-rush-title-first",
    "kind": "game-title",
    "game": "order-rush",
    "slot": "title",
    "value": "first",
    "name": "첫 영업",
    "price": null,
    "unlockOnly": true,
    "description": "주문 폭주 한 판 끝까지 마치기",
    "color": "#d4b786",
    "achievementId": "order-rush-first"
  },
  {
    "id": "order-rush-title-steady",
    "kind": "game-title",
    "game": "order-rush",
    "slot": "title",
    "value": "steady",
    "name": "주문을 기억하는 손",
    "price": null,
    "unlockOnly": true,
    "description": "누적 정답 20개",
    "color": "#d4b786",
    "achievementId": "order-rush-steady"
  },
  {
    "id": "order-rush-title-combo",
    "kind": "game-title",
    "game": "order-rush",
    "slot": "title",
    "value": "combo",
    "name": "빈틈없는 바리스타",
    "price": null,
    "unlockOnly": true,
    "description": "한 영업에서 주문 5개 연속 성공",
    "color": "#d4b786",
    "achievementId": "order-rush-combo"
  },
  {
    "id": "order-rush-title-perfect",
    "kind": "game-title",
    "game": "order-rush",
    "slot": "title",
    "value": "perfect",
    "name": "완벽한 마감",
    "price": null,
    "unlockOnly": true,
    "description": "한 판의 문제를 모두 맞힌 판 3회",
    "color": "#d4b786",
    "achievementId": "order-rush-perfect"
  },
  {
    "id": "entry-check-style-default",
    "kind": "game-style",
    "game": "entry-check",
    "slot": "style",
    "value": "default",
    "name": "기본 꾸미기",
    "price": 0,
    "description": "처음 함께한 기본 모습이에요.",
    "color": "#b7cdbb"
  },
  {
    "id": "entry-check-style-leaf",
    "kind": "game-style",
    "game": "entry-check",
    "slot": "style",
    "value": "leaf",
    "name": "잎새 도장",
    "price": 25,
    "description": "도장 둘레에 잎새 문양을 더해요.",
    "color": "#8abf9d"
  },
  {
    "id": "entry-check-style-postmark",
    "kind": "game-style",
    "game": "entry-check",
    "slot": "style",
    "value": "postmark",
    "name": "여행 소인",
    "price": 60,
    "description": "도장 둘레를 여행 우편 소인처럼 꾸며요.",
    "color": "#cd9f74"
  },
  {
    "id": "entry-check-style-star",
    "kind": "game-style",
    "game": "entry-check",
    "slot": "style",
    "value": "star",
    "name": "별무리 도장",
    "price": 100,
    "description": "도장 둘레에 작은 별 문양을 더해요.",
    "color": "#c7b3e6"
  },
  {
    "id": "entry-check-title-first",
    "kind": "game-title",
    "game": "entry-check",
    "slot": "title",
    "value": "first",
    "name": "첫 근무",
    "price": null,
    "unlockOnly": true,
    "description": "입장 검사 한 판 끝까지 마치기",
    "color": "#d4b786",
    "achievementId": "entry-check-first"
  },
  {
    "id": "entry-check-title-steady",
    "kind": "game-title",
    "game": "entry-check",
    "slot": "title",
    "value": "steady",
    "name": "초대장을 읽는 눈",
    "price": null,
    "unlockOnly": true,
    "description": "누적 정답 20개",
    "color": "#d4b786",
    "achievementId": "entry-check-steady"
  },
  {
    "id": "entry-check-title-combo",
    "kind": "game-title",
    "game": "entry-check",
    "slot": "title",
    "value": "combo",
    "name": "정확한 도장",
    "price": null,
    "unlockOnly": true,
    "description": "한 근무에서 첫 도장 5개 연속 정답",
    "color": "#d4b786",
    "achievementId": "entry-check-combo"
  },
  {
    "id": "entry-check-title-perfect",
    "kind": "game-title",
    "game": "entry-check",
    "slot": "title",
    "value": "perfect",
    "name": "믿음직한 문지기",
    "price": null,
    "unlockOnly": true,
    "description": "한 판의 문제를 모두 맞힌 판 3회",
    "color": "#d4b786",
    "achievementId": "entry-check-perfect"
  },
  {
    "id": "story-classroom-style-default",
    "kind": "game-style",
    "game": "story-classroom",
    "slot": "style",
    "value": "default",
    "name": "기본 꾸미기",
    "price": 0,
    "description": "처음 함께한 기본 모습이에요.",
    "color": "#b7cdbb"
  },
  {
    "id": "story-classroom-style-coral",
    "kind": "game-style",
    "game": "story-classroom",
    "slot": "style",
    "value": "coral",
    "name": "코랄 교실",
    "price": 25,
    "description": "이야기 수첩 표지와 교실 위쪽 장식을 따뜻한 코랄빛으로 꾸며요.",
    "color": "#e6a79a"
  },
  {
    "id": "story-classroom-style-blue",
    "kind": "game-style",
    "game": "story-classroom",
    "slot": "style",
    "value": "blue",
    "name": "하늘빛 교실",
    "price": 60,
    "description": "이야기 수첩 표지와 교실 위쪽 장식을 맑은 하늘빛으로 꾸며요.",
    "color": "#99bfd8"
  },
  {
    "id": "story-classroom-style-party",
    "kind": "game-style",
    "game": "story-classroom",
    "slot": "style",
    "value": "party",
    "name": "작은 축제",
    "price": 100,
    "description": "이야기 수첩 표지와 교실 위쪽 장식을 축제 색으로 꾸며요.",
    "color": "#c7b3e6"
  },
  {
    "id": "story-classroom-title-first",
    "kind": "game-title",
    "game": "story-classroom",
    "slot": "title",
    "value": "first",
    "name": "첫 이야기",
    "price": null,
    "unlockOnly": true,
    "description": "선생님이 돌아왔다 한 판 끝까지 마치기",
    "color": "#d4b786",
    "achievementId": "story-classroom-first"
  },
  {
    "id": "story-classroom-title-steady",
    "kind": "game-title",
    "game": "story-classroom",
    "slot": "title",
    "value": "steady",
    "name": "교실의 해결사",
    "price": null,
    "unlockOnly": true,
    "description": "도움 없이 첫 시도에 옮긴 부탁 누적 20개",
    "color": "#d4b786",
    "achievementId": "story-classroom-steady"
  },
  {
    "id": "story-classroom-title-combo",
    "kind": "game-title",
    "game": "story-classroom",
    "slot": "title",
    "value": "combo",
    "name": "척척 이야기꾼",
    "price": null,
    "unlockOnly": true,
    "description": "한 이야기에서 도움 없이 부탁 3개 연속 첫 시도 성공",
    "color": "#d4b786",
    "achievementId": "story-classroom-combo"
  },
  {
    "id": "story-classroom-title-perfect",
    "kind": "game-title",
    "game": "story-classroom",
    "slot": "title",
    "value": "perfect",
    "name": "완벽한 마지막 장",
    "price": null,
    "unlockOnly": true,
    "description": "모든 부탁을 도움 없이 첫 시도에 옮긴 이야기 3회",
    "color": "#d4b786",
    "achievementId": "story-classroom-perfect"
  },
  {
    "id": "blank-slice-style-default",
    "kind": "game-style",
    "game": "blank-slice",
    "slot": "style",
    "value": "default",
    "name": "기본 꾸미기",
    "price": 0,
    "description": "처음 함께한 기본 모습이에요.",
    "color": "#b7cdbb"
  },
  {
    "id": "blank-slice-style-blossom",
    "kind": "game-style",
    "game": "blank-slice",
    "slot": "style",
    "value": "blossom",
    "name": "벚꽃 검무",
    "price": 25,
    "description": "정답을 가르는 칼자국을 벚꽃빛으로 바꿔요.",
    "color": "#e5a3b1"
  },
  {
    "id": "blank-slice-style-ocean",
    "kind": "game-style",
    "game": "blank-slice",
    "slot": "style",
    "value": "ocean",
    "name": "파도 검무",
    "price": 60,
    "description": "정답을 가르는 칼자국을 바다빛으로 바꿔요.",
    "color": "#71bbd7"
  },
  {
    "id": "blank-slice-style-starlight",
    "kind": "game-style",
    "game": "blank-slice",
    "slot": "style",
    "value": "starlight",
    "name": "별빛 검무",
    "price": 100,
    "description": "정답을 가르는 칼자국을 별빛으로 바꿔요.",
    "color": "#c2b7ef"
  },
  {
    "id": "blank-slice-title-first",
    "kind": "game-title",
    "game": "blank-slice",
    "slot": "title",
    "value": "first",
    "name": "첫 베기",
    "price": null,
    "unlockOnly": true,
    "description": "빈칸 베기 한 판 끝까지 마치기",
    "color": "#d4b786",
    "achievementId": "blank-slice-first"
  },
  {
    "id": "blank-slice-title-steady",
    "kind": "game-title",
    "game": "blank-slice",
    "slot": "title",
    "value": "steady",
    "name": "표현을 모으는 검객",
    "price": null,
    "unlockOnly": true,
    "description": "누적 정답 베기 20개",
    "color": "#d4b786",
    "achievementId": "blank-slice-steady"
  },
  {
    "id": "blank-slice-title-combo",
    "kind": "game-title",
    "game": "blank-slice",
    "slot": "title",
    "value": "combo",
    "name": "끊김 없는 검무",
    "price": null,
    "unlockOnly": true,
    "description": "한 판에서 정답 5개 연속 베기",
    "color": "#d4b786",
    "achievementId": "blank-slice-combo"
  },
  {
    "id": "blank-slice-title-perfect",
    "kind": "game-title",
    "game": "blank-slice",
    "slot": "title",
    "value": "perfect",
    "name": "빈칸의 달인",
    "price": null,
    "unlockOnly": true,
    "description": "한 판의 문제를 모두 맞힌 판 3회",
    "color": "#d4b786",
    "achievementId": "blank-slice-perfect"
  }
]);
