// Generated by node tools/care-memory-theme.cjs. Do not edit.
export const memoryTheme = {
  "source": "Loom / docs/디자인_토큰.json",
  "colors": {
    "paper": "#FFFFFF",
    "ink": "#000000",
    "accent": "#AE322A"
  },
  "spaces": {
    "실": 2,
    "숨": 4,
    "틈": 8,
    "참": 12,
    "칸": 16,
    "단": 24,
    "켜": 40,
    "장": 64,
    "막": 104
  }
};
