import {experience,copy} from './data.js?v=e16032eea501';
const esc=value=>String(value??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
const named=(value,name)=>esc(value.replaceAll('{name}',name));
const image=(file,alt='',cls='scene-image')=>`<img class="${cls}" src="./assets/${file}.webp" alt="${esc(alt)}" width="1536" height="1024" loading="lazy">`;
const room=()=>`<figure class="room" aria-label="${esc(copy.ui.roomLabel)}"><img src="./assets/research.webp" width="1672" height="941" alt="${esc(copy.ui.roomAlt)}" fetchpriority="high"><img class="blink left" src="./assets/research-blink.webp" width="1672" height="941" alt="" aria-hidden="true"><img class="blink right" src="./assets/research-blink.webp" width="1672" height="941" alt="" aria-hidden="true"></figure>`;
const action=(id,label,cls='primary')=>`<button type="button" class="${cls}" data-action="${id}">${esc(label)}</button>`;
export function createViews(state){
 const person=()=>experience.people.find(p=>p.name===state.guide);
 const intro=()=>`<div class="intro"><div><span class="eyebrow">${esc(copy.page.eyebrow)}</span><h1 tabindex="-1">${esc(copy.page.stages[state.stage].title)}</h1><p class="subtitle">${esc(copy.page.stages[state.stage].subtitle)}</p></div><span class="experience-label">${esc(copy.page.badge)}</span></div><ol class="steps" aria-label="${esc(copy.ui.stepsLabel)}">${['story','write','review','done'].map(id=>`<li${state.stage===id?' aria-current="step"':''}>${esc(copy.page.stages[id].step)}</li>`).join('')}</ol>`;
 const context=()=>`<details class="task-reminder"><summary>${esc(copy.situation.mission)}</summary><dl class="clues">${copy.situation.clues.map(c=>`<div><dt>${esc(c.label)}</dt><dd>${esc(c.value)}</dd></div>`).join('')}</dl></details>`;
 const tone=()=>`<p class="tone-rule"><span aria-hidden="true">Aa</span>${esc(copy.ui.toneRule)}</p>`;
 const form=(review=false)=>`<form class="writing-card" id="letter-form"><div class="recipient">${room()}<div><span class="small-label">${esc(copy.ui.recipientLabel)}</span><strong>${esc(copy.ui.recipientName)}</strong></div></div>${tone()}<label for="letter-body">${esc(review?copy.ui.revisionLabel:copy.ui.letterLabel)}</label><textarea id="letter-body" name="letter" maxlength="6000" placeholder="${esc(review?copy.ui.reviewPlaceholder:copy.ui.placeholder)}" aria-describedby="writing-note writing-error">${esc(state.draft)}</textarea><p class="error" id="writing-error" role="alert"></p><button type="submit" class="primary">${esc(review?copy.ui.finish:copy.ui.reviewAction)} <span aria-hidden="true">→</span></button><p class="action-note" id="writing-note">${esc(review?copy.ui.finishNote:copy.ui.privacy)}</p></form>`;
 function story(){
  const p=person();
  return `<section class="story-brief" aria-labelledby="situation-title"><div class="professor-row">${room()}<div class="situation-copy"><h2 id="situation-title">${esc(copy.situation.title)}</h2><p>${esc(copy.situation.description)}</p><dl class="clues">${copy.situation.clues.map(c=>`<div><dt>${esc(c.label)}</dt><dd>${esc(c.value)}</dd></div>`).join('')}</dl></div></div></section><section class="guide-section" aria-labelledby="guide-title"><div class="section-heading"><h2 id="guide-title">${esc(copy.ui.guideTitle)}</h2><p>${esc(copy.ui.guideDescription)}</p></div><div class="guides" role="group" aria-label="${esc(copy.ui.guideGroup)}">${experience.people.map(g=>`<button type="button" class="guide" data-guide="${g.name}" aria-pressed="${state.guide===g.name}">${image(g.id,'','guide-avatar')}<span><strong>${g.name}</strong><span class="guide-note">${esc(state.guide===g.name?copy.ui.guideSelected:g.note)}</span></span></button>`).join('')}</div><div id="start-panel">${p?`<div class="start-panel"><div class="friend-line"><span class="small-label">${p.name}</span><p>${esc(p.welcome)}</p></div><div class="actions">${action('write',copy.ui.start)}<p class="action-note">${esc(copy.ui.startNote)}</p></div></div>`:''}</div></section>`;
 }
 function hints(){
  const p=person(),h=p.hints.find(h=>h.id===state.hint);
  return `<div class="hint-heading"><h3>${esc(copy.ui.hintsTitle)}</h3><p>${esc(state.hintsOpen?copy.ui.hintsDescription:copy.ui.hintClosed)}</p></div><button type="button" class="hint-toggle" data-action="toggle-hints" aria-expanded="${state.hintsOpen}" aria-controls="hint-content">${esc(state.hintsOpen?copy.ui.hintLess:copy.ui.hintOpen)} <span aria-hidden="true">${state.hintsOpen?'−':'+'}</span></button><div id="hint-content"${state.hintsOpen?'':' hidden'}>${state.hintsOpen?`<div class="hint-options" role="group" aria-label="${esc(copy.ui.hintsTitle)}">${p.hints.map(item=>`<button type="button" class="hint-option" data-hint="${item.id}" aria-pressed="${state.hint===item.id}">${image(p.strategies[item.id])}<span>${esc(item.title)}</span></button>`).join('')}</div>${h?`<div class="hint-answer" id="hint-answer" aria-live="polite"><span class="small-label">${p.name}</span><p>${esc(h.first)}</p>${state.hintMore?`<p class="second-hint">${esc(h.second)}</p>`:action('more-hint',copy.ui.hintMore,'quiet')}</div>`:''}`:''}</div>`;
 }
 function writing(){
  const p=person();
  return `${context()}${state.atlas?.focus()||''}<div class="writing-layout draft-layout">${form()}<aside class="companion-guide" aria-label="${esc(copy.ui.writingGuideLabel)}"><div class="companion-top">${image(p.id+'-notes',named(copy.ui.writingAlt,p.name))}<div class="friend-line"><span class="small-label">${p.name}</span><p>${esc(p.welcome)}</p></div></div><section class="hints-panel" id="hints-panel">${hints()}</section></aside></div><div class="actions">${action('story',copy.ui.backToStrategies,'quiet')}</div>`;
 }
 function review(){
  const p=person();
  return `${context()}<div class="writing-layout review-layout">${form(true)}<aside class="review-guide" aria-labelledby="review-title"><div class="review-intro">${image(p.id+'-plan',named(copy.ui.writingAlt,p.name))}<span class="small-label">${p.name}</span><p>${esc(p.review)}</p></div><h2 id="review-title">${esc(copy.ui.reviewTitle)}</h2><p class="review-description">${esc(copy.ui.reviewDescription)}</p><fieldset class="self-checks"><legend class="sr-only">${esc(copy.ui.reviewTitle)}</legend>${(state.atlas?.visibleChecks(copy.checks)||copy.checks).map(c=>`<label class="self-check"><input type="checkbox" data-check="${c.id}"${state.checks.includes(c.id)?' checked':''}><span><strong>${esc(c.label)}</strong><span>${esc(c.question)}</span></span></label>`).join('')}</fieldset>${state.atlas?.reviewMore(copy.checks)||''}${state.atlas?.extra()||''}<p class="action-note">${esc(copy.ui.reviewNote)}</p><details class="first-draft"><summary>${esc(copy.ui.initialLabel)}</summary><pre class="letter-original">${esc(state.initial)}</pre></details></aside></div><div class="actions">${action('write',copy.ui.backToWriting,'quiet')}</div>`;
 }
 function done(){
  const changed=state.final!==state.initial;
  return `<div class="done-heading"><h2>${esc(copy.ui.doneTitle)}</h2><p>${esc(copy.ui.doneDescription)}</p></div><div class="done-layout"><section class="your-letter"><span class="small-label">${esc(copy.ui.savedLabel)}</span><h3>${esc(copy.ui.recipientName)}</h3><pre class="letter-original">${esc(state.final)}</pre><div class="actions">${action('download',copy.ui.download)}${action('review',copy.ui.continueEditing,'quiet')}</div></section><aside class="done-art">${image('letter-studio',copy.ui.workshopAlt)}<p>${esc(copy.ui.privacy)}</p></aside></div>${changed?`<details class="draft-comparison"><summary>${esc(copy.ui.changesLabel)}</summary><div class="compare-grid"><section><h3>${esc(copy.ui.initialLabel)}</h3><pre class="letter-original">${esc(state.initial)}</pre></section><section><h3>${esc(copy.ui.revisionLabel)}</h3><pre class="letter-original">${esc(state.final)}</pre></section></div></details>`:`<p class="unchanged-note">${esc(copy.ui.noChanges)}</p>`}${state.atlas?.feedbackPanel()||''}<div class="actions">${action('restart',copy.ui.newRound,'quiet')}<a class="quiet" href="/#lab">${esc(copy.ui.labHome)} ↗</a></div>`;
 }
 return {intro,story,writing,review,done,hints,person};
}
